### ISSUE TITLE
unable to add this plugin

### ISSUE THREAD

**Issue by chistov** [apache/cordova-plugins#35]
# Bug Report
   I had tried to install your plugin and got connection error.

## Problem
   Unable to download and install plugin via command: 

cordova plugin add https://github.com/apache/cordova-plugins.git#wkwebview-engine-localhost

### What is expected to happen?
   Success installation.

### What does actually happen?

Got the error: 

 Failed to install 'cordova-labs-local-webserver': CordovaError: Failed to fetch plugin https://git-wip-us.apache.org/repos/asf/cordova-plugin-file.git via registry.
...
npm ERR! code ENOPACKAGEJSON

## Checklist

- [ ] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Something appears to be redirecting `https://github.com/apache/cordova-plugins.git#local-webserver` to `https://git-wip-us.apache.org/repos/asf/cordova-plugin-file.git`. I'd check to see if you have `package.json` entry for `cordova-labs-local-webserver` and `cordova-plugin-file`. If so then remove it and try to reinstall. I'd also delete the `package-lock.json` as well.

Additionally, these are unsupported experimental plugins not suitable for production use and I would **strongly** recommend you to use `cordova-ios@6` with schemes instead.

See link for more info: https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html
